version: '3'
services:
  postgres:
    container_name: postgres
    image: postgres
    ports:
      - 5433:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: app
    volumes:
      - ../apps/postgres:/var/lib/postgresql/data
